#!/bin/bash
# 🚀 Render Deployment Checklist

echo "✅ Brain Monitor Deployment Setup"
echo ""
echo "📋 Pre-Deployment Checklist:"
echo ""
echo "1. ✓ Backend files ready"
echo "   - backend/main.py (with Pinecone integration)"
echo "   - backend/requirements.txt"
echo "   - backend/.env (NOT committed - stays secret)"
echo "   - render.yaml (deployment config)"
echo ""
echo "2. ✓ Frontend configured"
echo "   - Frontend uses VITE_BACKEND_URL environment variable"
echo "   - Falls back to http://localhost:8000 for local dev"
echo ""
echo "Next steps:"
echo ""
echo "1️⃣  Push to GitHub:"
echo "   git add ."
echo "   git commit -m 'Add Render deployment ready'"
echo "   git push"
echo ""
echo "2️⃣  Deploy to Render:"
echo "   - Go to https://render.com"
echo "   - Sign in with GitHub"
echo "   - Click 'New +' → 'Blueprint'"
echo "   - Select your college_project repo"
echo ""
echo "3️⃣  Add Environment Variables:"
echo "   GEMINI_API_KEY: (from your .env)"
echo "   PINECONE_API_KEY: (from your .env)"
echo "   PINECONE_ENVIRONMENT: gcp-starter"
echo ""
echo "4️⃣  Deploy! (Render auto-deploys)"
echo ""
echo "5️⃣  Copy your Render URL and update frontend:"
echo "   VITE_BACKEND_URL=https://brain-monitor-api-xyz.render.com"
echo ""
echo "🎉 Done! Your stack is now:"
echo "   Frontend: http://localhost:5173 (local)"
echo "   Backend: https://render-app.render.com (cloud)"
echo "   Memory: Pinecone (persistent)"
echo ""
echo "See DEPLOY.md for detailed instructions"
